<a href="https://colab.research.google.com/github/arenas-franklin/api_financeira_pdf_relatorio/blob/main/API_financeira_pdf_relatorio.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# API financeira + PDF relátorio
---

**descrição:**
- Buscar dados financeiros das ações da Petrobras usando o YFINANCE
- Criar análise financeiras sobre as ações usando frameworks PLOTLY
- Criar o layout do PDF usadno o MAKE_sIBPLOT do PLOTY
- Exportação automática do relório em PDF

In [2]:
!pip install yfinance --upgrade --no-cache-dir

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting yfinance
  Downloading yfinance-0.2.11-py2.py3-none-any.whl (59 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 59.2/59.2 KB 5.0 MB/s eta 0:00:00
Collecting cryptography>=3.3.2
  Downloading cryptography-39.0.1-cp36-abi3-manylinux_2_28_x86_64.whl (4.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 66.2 MB/s eta 0:00:00
Requirement already satisfied: lxml>=4.9.1 in /usr/local/lib/python3.8/dist-packages (from yfinance) (4.9.2)
Collecting html5lib>=1.1
  Downloading html5lib-1.1-py2.py3-none-any.whl (112 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 112.2/112.2 KB 60.9 MB/s eta 0:00:00
Requirement already satisfied: numpy>=1.16.5 in /usr/local/lib/python3.8/dist-packages (from yfinance) (1.21.6)
Requirement already satisfied: pytz>=2022.5 in /usr/local/lib/python3.8/dist-packages (from yfinance) (2022.7.1)
Collecting beautifulsoup4>=4.11.1
  Downloading beautifulsoup4-4.11.2-py3-none-any.whl (129 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 129.4/129.4 KB 240.4 MB/s eta 0:00:00
Collecting frozendict>=2.3.4
  Downloading frozendict-2.3.4-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (110 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 111.0/111.0 KB 256.7 MB/s eta 0:00:00
Collecting requests>=2.26
  Downloading requests-2.28.2-py3-none-any.whl (62 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.8/62.8 KB 196.5 MB/s eta 0:00:00
Requirement already satisfied: appdirs>=1.4.4 in /usr/local/lib/python3.8/dist-packages (from yfinance) (1.4.4)
Requirement already satisfied: pandas>=1.3.0 in /usr/local/lib/python3.8/dist-packages (from yfinance) (1.3.5)
Requirement already satisfied: multitasking>=0.0.7 in /usr/local/lib/python3.8/dist-packages (from yfinance) (0.0.11)
Collecting soupsieve>1.2
  Downloading soupsieve-2.3.2.post1-py3-none-any.whl (37 kB)
Requirement already satisfied: cffi>=1.12 in /usr/local/lib/python3.8/dist-packages (from cryptography>=3.3.2->yfinance) (1.15.1)
Requirement already satisfied: six>=1.9 in /usr/local/lib/python3.8/dist-packages (from html5lib>=1.1->yfinance) (1.15.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.8/dist-packages (from html5lib>=1.1->yfinance) (0.5.1)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.8/dist-packages (from pandas>=1.3.0->yfinance) (2.8.2)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.8/dist-packages (from requests>=2.26->yfinance) (1.24.3)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.8/dist-packages (from requests>=2.26->yfinance) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.8/dist-packages (from requests>=2.26->yfinance) (2022.12.7)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.8/dist-packages (from requests>=2.26->yfinance) (2.1.1)
Requirement already satisfied: pycparser in /usr/local/lib/python3.8/dist-packages (from cffi>=1.12->cryptography>=3.3.2->yfinance) (2.21)
Installing collected packages: soupsieve, requests, html5lib, frozendict, cryptography, beautifulsoup4, yfinance
  Attempting uninstall: requests
    Found existing installation: requests 2.25.1
    Uninstalling requests-2.25.1:
      Successfully uninstalled requests-2.25.1
  Attempting uninstall: html5lib
    Found existing installation: html5lib 1.0.1
    Uninstalling html5lib-1.0.1:
      Successfully uninstalled html5lib-1.0.1
  Attempting uninstall: beautifulsoup4
    Found existing installation: beautifulsoup4 4.6.3
    Uninstalling beautifulsoup4-4.6.3:
      Successfully uninstalled beautifulsoup4-4.6.3
Successfully installed beautifulsoup4-4.11.2 cryptography-39.0.1 frozendict-2.3.4 html5lib-1.1 requests-2.28.2 soupsieve-2.3.2.post1 yfinance-0.2.11

In [3]:
# importando pacotes 
#pacotes analise de dados
import pandas as pd
import pandas_datareader.data as web
import numpy as np

# pacotes para analise graficca
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.graph_objects as go
import plotly.express as px
from plotly.subplots import make_subplots

# pacotes para data
from datetime import datetime 

#YFinance
import yfinance as yf
yf.pdr_override()

# Avisos
import warnings
warnings.filterwarnings('ignore')

## API Yahoo Finance

In [5]:
# Coletando os dados
Dados  = web.get_data_yahoo('PETR4.SA', period='1y')

# Shape
Dados.shape

[*********************100%***********************]  1 of 1 completed

(252, 6)

In [6]:
# verificando os primerios registros 
Dados.head()

                 Open       High        Low      Close  Adj Close    Volume
Date
2022-02-10  32.299999  32.900002  31.940001  32.439999  18.958057  49534600
2022-02-11  32.770000  33.910000  32.630001  33.759998  19.729469  88013400
2022-02-14  33.860001  33.939999  32.820000  33.000000  19.285324  55687000
2022-02-15  32.660000  32.680000  31.889999  32.480000  18.981434  65689000
2022-02-16  32.830002  33.700001  32.770000  32.930000  19.244417  65811600

In [7]:
# os ultimos registros
Dados.tail()

                 Open       High        Low      Close  Adj Close    Volume
Date
2023-02-06  24.870001  25.870001  24.750000  25.780001  25.780001  82794500
2023-02-07  25.910000  26.139999  25.459999  25.620001  25.620001  55311800
2023-02-08  25.799999  26.150000  25.559999  26.049999  26.049999  48713100
2023-02-09  26.049999  26.320000  25.790001  25.930000  25.930000  38198300
2023-02-10  25.980000  26.790001  25.930000  26.719999  26.719999  54683100

In [8]:
#Estatistica descritiva
Dados.describe()

             Open        High         Low       Close   Adj Close        Volume
count  252.000000  252.000000  252.000000  252.000000  252.000000  2.520000e+02
mean    29.936190   30.476587   29.394960   29.951944   23.394864  8.192431e+07
std      3.663650    3.681757    3.621338    3.648793    3.532174  3.683580e+07
min     21.000000   22.110001   20.770000   21.469999   17.537958  2.876520e+07
25%     26.995000   27.545000   26.167500   26.930000   20.008966  5.612075e+07
50%     30.750000   31.339999   30.205000   30.605000   23.325000  7.285520e+07
75%     32.717501   33.507500   32.382501   32.967500   26.070860  9.630120e+07
max     37.650002   38.389999   36.849998   37.720001   33.003029  3.195016e+08

In [9]:
#informações
Dados.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 252 entries, 2022-02-10 to 2023-02-10
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Open       252 non-null    float64
 1   High       252 non-null    float64
 2   Low        252 non-null    float64
 3   Close      252 non-null    float64
 4   Adj Close  252 non-null    float64
 5   Volume     252 non-null    int64
dtypes: float64(5), int64(1)
memory usage: 13.8 KB

### Media Móvel